py_library(
    name = "blueprint",
    srcs = [
        "blueprint.py",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "maps",
    srcs = glob([
        "maps/*.xodr",
    ]),
    visibility = ["//visibility:public"],
)
