py_library(
    name = "belief_observer",
    srcs = [
        "belief_observer.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bark_ml_project//bark_ml/observers",
    ],
)
