py_library(
    name = "dispatcher",
    srcs = [
        "dispatcher.py",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "sequential_dispatcher",
    srcs = [
        "sequential_dispatcher.py",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "parallel_dispatcher",
    srcs = [
        "parallel_dispatcher.py",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "remote_dispatcher",
    srcs = [
        "remote_dispatcher.py",
    ],
    visibility = ["//visibility:public"],
)
